-- | Compile the packaged auth plane into one reviewed owner scope. Images are
-- immutable inputs; credential values are generated by the Kubernetes adapter
-- only after confirmed Secret absence.
module Nagare.Inventory.Components.Auth
  ( AuthInput (..)
  , AuthMode (..)
  , compileAuth
  , compileAuthComponent
  ) where

import Control.Exception (IOException, try)
import Data.Aeson (Value (..), object, (.=))
import Data.Aeson.KeyMap qualified as KM
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Generics.Labels ()
import Data.List.NonEmpty (NonEmpty (..))
import Data.Map.Strict (Map)
import Data.Map.Strict qualified as Map
import Data.Text (Text)
import Data.Text qualified as T
import Data.Text.Encoding qualified as TE
import Data.Vector qualified as V
import Nagare.Dsl.Prelude hiding ((.=))
import Nagare.Cluster.GcsJob (StoreBackend)
import Nagare.Dsl.Types (databaseNameText)
import Nagare.Inventory.Components.Upstream
import Nagare.Inventory.Database (compileDatabaseForBackend)
import Nagare.Inventory.Digest (contentDigest)
import Nagare.Resource.Database (DatabaseDirectInput (..), databaseResourceId)
import Nagare.Resource.Inventory
import Nagare.Resource.Kubernetes
import Nagare.Resource.Policy (LifecyclePolicy (Protect), RecoveryClass (VerifyBeforeRetry))
import Nagare.Resource.Reference (Dependency (OrderedAfter))
import Nagare.Resource.Types
import System.FilePath ((</>))

data AuthMode = CloudAuth | LocalAuth deriving stock (Eq, Show)

data AuthInput = AuthInput
  { authOwner :: !ScopeId
  , authCluster :: !ResourceId
  , authNamespace :: !ResourceId
  , authRoot :: !FilePath
  , authImages :: !(Map Text Text)
  , authBaseDomain :: !Text
  , authDatabasePrerequisites :: !(Map Text ResourceId)
  , authMode :: !AuthMode
  }

-- | The two auth databases and workloads share one complete owner scope.
-- Callers provide the full typed Database values, not a reconstructed flag set.
compileAuthComponent
  :: AuthInput
  -> [(Text, DatabaseDirectInput, StoreBackend)]
  -> IO (Either (NonEmpty InventoryError) (ScopeDeclaration, Map ResourceId (ManagedResource, ByteString)))
compileAuthComponent input databases = do
  compiledAuth <- compileAuth input
  pure $ do
    (authBundle, authNative) <- compiledAuth
    unless (map (\(service, _, _) -> service) databases == ["shomei", "en"])
      (Left (single "auth database inputs must name shomei and en in order"))
    compiledDatabases <- traverse compileDatabase databases
    let bundles = authBundle : map fst compiledDatabases
        nativeMaps = authNative : map snd compiledDatabases
        native = Map.unions nativeMaps
    unless (Map.size native == sum (map Map.size nativeMaps))
      (Left (single "auth database and workload native members overlap"))
    scope <- mkScopeDeclaration (authOwner input) bundles
    pure (scope, native)
  where
    single message = (inventoryError "invalid-auth-component" message
      & #scopes .~ [authOwner input]) :| []
    compileDatabase (service, direct, backend) = do
      unless (directOwnerScope direct == authOwner input
          && directClusterId direct == authCluster input
          && directNamespaceId direct == Just (authNamespace input)
          && databaseNameText (directDatabase direct ^. #name) == service <> "-db")
        (Left (single "auth database does not match the owner, cluster, Namespace, or service"))
      expected <- first (single . T.pack . show)
        (databaseResourceId (authOwner input) (either (error . T.unpack) id (mkName "statefulset"))
          (directDatabase direct))
      unless (Map.lookup service (authDatabasePrerequisites input) == Just expected)
        (Left (single "auth database dependency differs from its typed direct bundle"))
      compileDatabaseForBackend direct backend

compileAuth
  :: AuthInput
  -> IO (Either (NonEmpty InventoryError) (ResourceBundle, Map ResourceId (ManagedResource, ByteString)))
compileAuth input = do
  loaded <- traverse loadManifest packaged
  case sequence loaded of
    Left message -> pure (Left (single message))
    Right sources -> do
      let transformed = concat <$> traverse transformSource (concat sources)
      case transformed of
        Left message -> pure (Left (single message))
        Right objects -> do
          let upstream = UpstreamInput
                { upstreamOwner = authOwner input
                , upstreamCluster = authCluster input
                , upstreamKey = knownKey "auth"
                , upstreamRoot = authRoot input
                , upstreamFiles = []
                , upstreamNamespaces = Map.singleton (known "nagare-system") (authNamespace input)
                , upstreamTransferred = mempty
                , upstreamConfigMapData = Map.empty
                , upstreamGenerated = objects <> map secretTemplate
                    ["nagare-access", "nagare-en-api-keys", "nagare-shomei-keys"]
                , upstreamAfter = internalOrder
                , upstreamOrderDeployments = False
                }
          compiled <- compileUpstream upstream
          pure $ do
            (bundle, native) <- compiled
            let migrationJobs = [(resource, bytes) | (resource, bytes) <- Map.elems native,
                  case resource ^. #address of
                    Kubernetes _ "batch" kind _ _ -> nameText kind == "job"
                    _ -> False]
                proofId resource = case resource ^. #address of
                  Kubernetes _ _ _ _ name -> mintResourceId (authOwner input)
                    (knownKey "auth") (known ("proof-" <> nameText name))
                  _ -> error "auth migration proof has no Kubernetes address"
                proofs = [DeclaredOperation (proofId resource) (resource ^. #identity :| [])
                    [ContentInput (contentDigest bytes)] VerifyBeforeRetry SchemaMigration
                  | (resource, bytes) <- migrationJobs]
                proofFor service = [proofId resource | (resource, _) <- migrationJobs,
                  case resource ^. #address of
                    Kubernetes _ _ _ _ name -> service `T.isPrefixOf` nameText name
                    _ -> False]
                addExternal resource = case resource ^. #address of
                  Kubernetes _ "" kind _ _ | nameText kind == "secret" ->
                    resource {lifecycle = Protect}
                  Kubernetes _ _ kind _ name
                    | nameText kind `elem` ["job", "deployment"] ->
                        let service = if "en" `T.isPrefixOf` nameText name then "en" else "shomei"
                         in case Map.lookup service (authDatabasePrerequisites input) of
                              Just databaseId -> resource
                                {dependencies = map OrderedAfter
                                    (databaseId : if nameText kind == "deployment" then proofFor service else [])
                                    <> resource ^. #dependencies}
                              Nothing -> resource
                  _ -> resource
                updated = Map.map (\(resource, bytes) -> (addExternal resource, bytes)) native
                byId = Map.map fst updated
                update (Managed resource) = Managed (Map.findWithDefault resource (resource ^. #identity) byId)
                update declaration = declaration
            unless (all (`Map.member` authDatabasePrerequisites input) ["en", "shomei"])
              (Left (single "auth database prerequisite is missing"))
            pure (bundle {declarations = map update (declarations bundle), operations = proofs}, updated)
  where
    single message = (inventoryError "invalid-auth-component" message
      & #scopes .~ [authOwner input]) :| []
    known = either (error . T.unpack) id . mkName
    knownKey = either (error . T.unpack) id . mkLogicalKey
    packaged =
      [ ("cluster/bootstrap/shomei/migrations.yaml", "ad92056638ae97ccf2dec2921b72f1d027e3b238a3c1c70819ffc6ebc725096e")
      , ("cluster/bootstrap/en/migrations.yaml", "45cf0132d346e43cf307ed23ddb98dd6c0a74f3f4249c1373a9d54b0d8028f0b")
      , ("cluster/bootstrap/en/configmap.yaml", "9fad4c79902738e6882915f79588813ceecfded240e6938dd348d3ccd5dfef6a")
      , ("cluster/bootstrap/nagare-access/configmap.yaml", "195cf7c08a5f8645207f5ba51cf4818a1ad6f9f59f4a8c7f39685a70e92344ab")
      , ("cluster/bootstrap/shomei/service.yaml", "5d5e0a1470764e4a77f717a52d5a0e74e4d61b69056629e8a5bd615b11ea8f72")
      , ("cluster/bootstrap/en/service.yaml", "9ed0b83a91c0e3855e4574f2998cbc7ed9161701f5ba173ff9b723e968714a1a")
      , ("cluster/bootstrap/nagare-access/service.yaml", "bf33f987d1bc27d565b3b5490a6f4c1291c96240b1610e7bb146b238228de9a1")
      ]
    loadManifest (relative, expected) = do
      loaded <- try (BS.readFile (authRoot input </> relative)) :: IO (Either IOException ByteString)
      pure $ do
        bytes <- first (T.pack . show) loaded
        digest <- mkContentDigest expected
        unless (contentDigest bytes == digest) (Left "packaged auth manifest differs from its pinned digest")
        first (T.pack . show) (parseKubernetesManifest (SourceLocation (T.pack relative) "auth") bytes)
    transformSource (location, value) = do
      case value of
        Object root | KM.lookup "kind" root == Just (String "Namespace") -> Right []
        _ -> do
          rendered <- renderTemplateValue value
          withMode <- case authMode input of
            LocalAuth -> addLocalShomeiEnv rendered
            CloudAuth -> Right rendered
          revised <- reviseJob withMode
          pure [(location, revised)]
    renderTemplateValue (String value)
      | Just image <- Map.lookup value imagePlaceholders = String <$> imageFor image
      | value == "${NAGARE_ACCESS_COOKIE_DOMAIN}" =
          Right (String ("." <> authBaseDomain input))
      | "${" `T.isInfixOf` value = Left "auth template has an unresolved placeholder"
      | otherwise = Right (String value)
    renderTemplateValue (Object fields) = Object <$> traverse renderTemplateValue fields
    renderTemplateValue (Array values) = Array <$> traverse renderTemplateValue values
    renderTemplateValue value = Right value
    imagePlaceholders = Map.fromList
      [("${NAGARE_REGISTRY_PREFIX}/" <> service <> ":${NAGARE_AUTH_TAG}", service)
      | service <- ["en", "shomei", "nagare-access"]]
    imageFor service = do
      image <- maybe (Left ("auth image is missing: " <> service)) Right
        (Map.lookup service (authImages input))
      unless (case T.splitOn "@sha256:" image of
        [repository, digest] -> not (T.null repository) && T.length digest == 64
          && T.all (`elem` (['0'..'9'] <> ['a'..'f'])) digest
        _ -> False)
        (Left "auth image must use an immutable sha256 digest")
      pure image
    reviseJob (Object root) | KM.lookup "kind" root == Just (String "Job") = do
      metadata <- case KM.lookup "metadata" root of
        Just (Object fields) -> Right fields
        _ -> Left "auth Job has no metadata"
      name <- case KM.lookup "name" metadata of
        Just (String textName) -> Right textName
        _ -> Left "auth Job has no name"
      let imageName = if "en" `T.isPrefixOf` name then "en" else "shomei"
      image <- imageFor imageName
      let suffix = T.take 12 (digestText (contentDigest (TE.encodeUtf8 image)))
      pure (Object (KM.insert "metadata" (Object (KM.insert "name" (String (name <> "-" <> suffix)) metadata)) root))
    reviseJob value = Right value
    addLocalShomeiEnv value@(Object root)
      | KM.lookup "kind" root == Just (String "Deployment") = do
          metadata <- case KM.lookup "metadata" root of
            Just (Object fields) -> Right fields
            _ -> Left "auth Deployment has no metadata"
          case KM.lookup "name" metadata of
            Just (String "shomei") -> updateAt ["spec", "template", "spec", "containers"] appendShomeiEnv value
            _ -> Right value
    addLocalShomeiEnv value = Right value
    appendShomeiEnv (Array containers) = case V.uncons containers of
      Just (Object container, rest) -> do
        unless (KM.lookup "name" container == Just (String "shomei"))
          (Left "Shomei Deployment first container has an unexpected name")
        values <- case KM.lookup "env" container of
          Just (Array items) -> Right items
          _ -> Left "Shomei Deployment has no env array"
        let extras = V.fromList
              [object ["name" .= ("SHOMEI_WEBAUTHN_RP_ID" :: Text), "value" .= authBaseDomain input]
              , object ["name" .= ("SHOMEI_WEBAUTHN_ORIGINS" :: Text),
                  "value" .= ("https://protected-hello." <> authBaseDomain input)]
              ]
        pure (Array (V.cons (Object (KM.insert "env" (Array (values <> extras)) container)) rest))
      _ -> Left "Shomei Deployment has no first container"
    appendShomeiEnv _ = Left "Shomei Deployment containers are malformed"
    updateAt [] change value = change value
    updateAt (field : remaining) change (Object fields) = do
      current <- maybe (Left "auth template lacks expected nested field") Right (KM.lookup field fields)
      updated <- updateAt remaining change current
      pure (Object (KM.insert field updated fields))
    updateAt _ _ _ = Left "auth template has a malformed nested field"
    secretTemplate name = (SourceLocation "generated:auth-credential" name, object
      [ "apiVersion" .= ("v1" :: Text)
      , "kind" .= ("Secret" :: Text)
      , "metadata" .= object
          [ "name" .= (name :: Text)
          , "namespace" .= ("nagare-system" :: Text)
          , "annotations" .= object ["nagare.dev/auth-credential-template" .= ("v1" :: Text)]
          ]
      , "type" .= ("Opaque" :: Text)
      ])
    address group kind name = either (error . T.unpack) id
      (kubernetesAddress (authCluster input) group kind (Just "nagare-system") name)
    job service = do
      image <- imageFor service
      let suffix = T.take 12 (digestText (contentDigest (TE.encodeUtf8 image)))
      pure (address "batch/v1" "Job" (service <> "-migrate-" <> suffix))
    internalOrder = either (const Map.empty) id $ do
      shomeiJob <- job "shomei"
      enJob <- job "en"
      pure (Map.fromList
        [ (address "apps/v1" "Deployment" "shomei", [shomeiJob, address "v1" "Secret" "nagare-shomei-keys"])
        , (address "apps/v1" "Deployment" "en", [enJob, address "v1" "Secret" "nagare-en-api-keys", address "v1" "ConfigMap" "en-schema"])
        , (address "serving.knative.dev/v1" "Service" "nagare-access",
            [address "apps/v1" "Deployment" "shomei", address "apps/v1" "Deployment" "en",
             address "v1" "Secret" "nagare-access", address "v1" "ConfigMap" "nagare-access-backends"])
        ])
