{-# LANGUAGE OverloadedStrings #-}

-- | Redis managed-database descriptor (see the Postgres fixture for the full
-- explanation). The password is generated by @nagarectl db create@ (EP-45), not
-- declared here.
module Main (main) where

import Data.Bifunctor (first)
import Nagare.Dsl.Config (emitDatabase)
import Nagare.Dsl.Database
import Nagare.Dsl.Types (RetentionPolicy (..), mkNamespace, mkQuantity)

database :: Either String Database
database = do
  n <- first show (mkDatabaseName "redis-cache")
  v <- first show (mkEngineVersion Redis "8")
  ns <- first show (mkNamespace "personal")
  sz <- first show (mkQuantity "2Gi")
  Right
    Database
      { dbName = n
      , engine = Redis
      , version = v
      , namespace = ns
      , size = sz
      , resources = Nothing
      , retention = Retain
      }

main :: IO ()
main = case database of
  Left err -> ioError (userError err)
  Right db -> emitDatabase db
