-- | Assemble the temporary Docker build context for a static site release.
--
-- The image is generated, never hand-written (MasterPlan Integration Point 3):
-- an Nginx base image that serves the built files from
-- @/usr/share/nginx/html@ on port 8080, with the generated server config copied
-- over Nginx's @default.conf@. 'withStaticImageContext' writes that context into
-- a temp directory and hands the path to a continuation (typically
-- 'Nagare.Image.buildImage'); the temp directory is removed on exit, so a
-- partial failure leaves nothing behind.
--
-- The layout written is:
--
-- > <ctx>/Dockerfile
-- > <ctx>/nginx.conf
-- > <ctx>/site/...        (the prepared static output)
module Nagare.Static.Image
  ( staticDockerfile
  , withStaticImageContext
  ) where

import Cradle
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Nagare.Dsl.Static.Render (renderNginxConfig)
import Nagare.Dsl.Static.Types (StaticSite)
import Nagare.Static.Build (PreparedStaticOutput (..))
import System.FilePath ((</>))
import System.IO.Temp (withSystemTempDirectory)

-- | The generated Dockerfile for every static-site release. The Nginx config
-- generated by EP-13 listens on 8080, the port Knative routes to.
staticDockerfile :: ByteString
staticDockerfile =
  BS.intercalate
    "\n"
    [ "FROM nginx:1.27-alpine"
    , "COPY nginx.conf /etc/nginx/conf.d/default.conf"
    , "COPY site/ /usr/share/nginx/html/"
    , "EXPOSE 8080"
    , ""
    ]

-- | Build the temp image context for @site@ from its @prepared@ output, then run
-- @action@ with the context directory path. The directory is cleaned up when
-- @action@ returns or throws.
withStaticImageContext ::
  StaticSite -> PreparedStaticOutput -> (FilePath -> IO a) -> IO a
withStaticImageContext site prepared action =
  withSystemTempDirectory "nagare-static-ctx" $ \ctx -> do
    let siteDir = ctx </> "site"
    -- Create site/ and copy the prepared output's *contents* into it. `cp -R
    -- <out>/. <siteDir>` copies the directory contents, not the directory
    -- itself, so files land directly under site/.
    run_ $ cmd "mkdir" & addArgs ["-p", siteDir]
    run_ $ cmd "cp" & addArgs ["-R", outputDirectory prepared <> "/.", siteDir]
    BS.writeFile (ctx </> "nginx.conf") (renderNginxConfig site)
    BS.writeFile (ctx </> "Dockerfile") staticDockerfile
    action ctx
