{-# LANGUAGE OverloadedStrings #-}

-- | ClickHouse managed-database descriptor (see the Postgres fixture for the
-- full explanation). The password is generated by @nagarectl db create@
-- (EP-45), not declared here.
module Main (main) where

import Data.Bifunctor (first)
import Nagare.Dsl.Config (emitDatabase)
import Nagare.Dsl.Database
import Nagare.Dsl.Types (RetentionPolicy (..), mkNamespace, mkQuantity)

database :: Either String Database
database = do
  n <- first show (mkDatabaseName "analytics")
  v <- first show (mkEngineVersion ClickHouse "25.8")
  ns <- first show (mkNamespace "personal")
  sz <- first show (mkQuantity "5Gi")
  Right
    Database
      { dbName = n
      , engine = ClickHouse
      , version = v
      , namespace = ns
      , size = sz
      , resources = Nothing
      , retention = Retain
      }

main :: IO ()
main = case database of
  Left err -> ioError (userError err)
  Right db -> emitDatabase db
