{-# LANGUAGE OverloadedStrings #-}

-- | Validated, context-owned NixOS host configuration.
module Nagare.Host.Config
  ( HostConfig (..)
  , HostInstallResult (..)
  , hostConfigDir
  , installHostFlake
  , readAuthorizedKeys
  , renderHostFlake
  , renderHostModule
  , renderHostSummary
  , validateSshPublicKey
  )
where

import Control.Exception (IOException, onException, try)
import Control.Monad (when)
import Data.ByteString qualified as BS
import Data.Char (isAlphaNum)
import Data.List.NonEmpty (NonEmpty (..))
import Data.List.NonEmpty qualified as NonEmpty
import Data.Text (Text)
import Data.Text qualified as T
import Data.Text.IO qualified as TIO
import Nagare.Target (ContextName, contextNameText, nagareConfigDir)
import Nagare.Version (BuildVersion (..))
import System.Directory
  ( copyFile
  , createDirectoryIfMissing
  , doesDirectoryExist
  , doesFileExist
  , makeAbsolute
  , removePathForcibly
  , renameDirectory
  )
import System.Exit (ExitCode (..))
import System.FilePath (takeDirectory, (</>))
import System.IO.Temp (createTempDirectory)
import System.Process (readProcessWithExitCode)

data HostConfig = HostConfig
  { hostContext :: !ContextName
  , hostName :: !Text
  , instanceName :: !Text
  , registryHost :: !Text
  , deployUser :: !Text
  , authorizedKeys :: !(NonEmpty Text)
  , ageKeyFile :: !FilePath
  , nagareNixosSource :: !FilePath
  }
  deriving stock (Eq, Show)

data HostInstallResult = HostInstalled | HostReplaced | HostUnchanged
  deriving stock (Eq, Show)

hostConfigDir :: ContextName -> IO FilePath
hostConfigDir context = do
  root <- nagareConfigDir
  pure (root </> "hosts" </> T.unpack (contextNameText context))

validateSshPublicKey :: Text -> Either Text Text
validateSshPublicKey raw
  | T.any (`elem` ['\n', '\r']) raw = Left "SSH public key must be one line"
  | "PRIVATE KEY" `T.isInfixOf` T.toUpper raw = Left "refusing private-key material; provide a public .pub file"
  | otherwise = case T.words (T.strip raw) of
      keyType : encoded : _
        | not (validKeyType keyType) -> Left ("unsupported SSH public-key type: " <> keyType)
        | T.length encoded < 16 || not (T.all validBase64Char encoded) -> Left "SSH public key has invalid base64 data"
        | otherwise -> Right (T.strip raw)
      _ -> Left "SSH public key must contain a key type and base64 payload"
  where
    validKeyType keyType =
      keyType `elem` ["ssh-ed25519", "ssh-rsa"]
        || "ecdsa-sha2-" `T.isPrefixOf` keyType
        || "sk-ssh-ed25519@" `T.isPrefixOf` keyType
        || "sk-ecdsa-sha2-" `T.isPrefixOf` keyType
    validBase64Char c = isAlphaNum c || c `elem` ['+', '/', '=']

readAuthorizedKeys :: [FilePath] -> IO (Either Text (NonEmpty Text))
readAuthorizedKeys [] = pure (Left "at least one --ssh-public-key-file is required")
readAuthorizedKeys paths = do
  results <- traverse readOne paths
  pure $ do
    keys <- sequence results
    case NonEmpty.nonEmpty keys of
      Nothing -> Left "at least one --ssh-public-key-file is required"
      Just nonEmptyKeys -> Right nonEmptyKeys
  where
    readOne path = do
      contentResult <- try (TIO.readFile path) :: IO (Either IOException Text)
      pure $ case contentResult of
        Left err -> Left ("could not read SSH public-key file " <> T.pack path <> ": " <> T.pack (show err))
        Right content -> case filter (not . ignored) (T.lines content) of
          [line] -> validateSshPublicKey line
          [] -> Left ("SSH public-key file is empty: " <> T.pack path)
          _ -> Left ("SSH public-key file must contain exactly one public key: " <> T.pack path)
    ignored line = T.null stripped || "#" `T.isPrefixOf` stripped
      where
        stripped = T.strip line

renderHostFlake :: HostConfig -> BuildVersion -> Text
renderHostFlake config buildVersion =
  T.unlines
    [ "{"
    , "  description = " <> nixString ("Nagare host " <> contextNameText (hostContext config)) <> ";"
    , ""
    , "  # Generated by nagarectl " <> versionText buildVersion <> "; EP-108 updates only this input."
    , "  inputs.nagare.url = " <> nixString ("path:" <> T.pack (nagareNixosSource config)) <> ";"
    , ""
    , "  outputs = { self, nagare }:"
    , "    let"
    , "      hostSystem = nagare.lib.mkNagareSystem { hostModule = ./host.nix; };"
    , "    in {"
    , "      nixosConfigurations." <> nixString (hostName config) <> " = hostSystem;"
    , "      packages.x86_64-linux.nagare-image = hostSystem.config.system.build.image;"
    , "    };"
    , "}"
    ]

renderHostModule :: HostConfig -> Text
renderHostModule config =
  T.unlines
    [ "{ ... }:"
    , ""
    , "{"
    , "  nagare.host = {"
    , "    hostName = " <> nixString (hostName config) <> ";"
    , "    instanceName = " <> nixString (instanceName config) <> ";"
    , "    registryHost = " <> nixString (registryHost config) <> ";"
    , "    deployUser = " <> nixString (deployUser config) <> ";"
    , "    authorizedKeys = ["
    ]
    <> T.concat ["      " <> nixString key <> "\n" | key <- NonEmpty.toList (authorizedKeys config)]
    <> T.unlines
      [ "    ];"
      , "    sopsDefaultFile = ./secrets.yaml;"
      , "    ageKeyFile = " <> nixString (T.pack (ageKeyFile config)) <> ";"
      , "  };"
      , "}"
      ]

renderHostSummary :: FilePath -> HostConfig -> Text
renderHostSummary root config =
  T.unlines
    [ "context: " <> contextNameText (hostContext config)
    , "path: " <> T.pack root
    , "hostName: " <> hostName config
    , "instanceName: " <> instanceName config
    , "registryHost: " <> registryHost config
    , "deployUser: " <> deployUser config
    , "authorizedKeys: " <> T.pack (show (NonEmpty.length (authorizedKeys config)))
    , "ageKeyFile: " <> T.pack (ageKeyFile config)
    , "nagareInput: path:" <> T.pack (nagareNixosSource config)
    ]

installHostFlake :: Bool -> HostConfig -> BuildVersion -> Maybe FilePath -> IO (Either Text HostInstallResult)
installHostFlake force config buildVersion requestedSopsFile = do
  destination <- hostConfigDir (hostContext config)
  sourceResult <- resolveSopsSource destination requestedSopsFile
  case sourceResult of
    Left err -> pure (Left err)
    Right sopsSource -> do
      let parent = takeDirectory destination
      createDirectoryIfMissing True parent
      staging <- createTempDirectory parent ("." <> T.unpack (contextNameText (hostContext config)) <> ".staging.")
      let cleanup = removeIfPresent staging
      (do
          TIO.writeFile (staging </> "flake.nix") (renderHostFlake config buildVersion)
          TIO.writeFile (staging </> "host.nix") (renderHostModule config)
          copyFile sopsSource (staging </> "secrets.yaml")
          hygiene <- validateGeneratedTree staging
          case hygiene of
            Left err -> cleanup >> pure (Left err)
            Right () -> do
              validation <- validateNixFlake staging
              case validation of
                Left err -> cleanup >> pure (Left err)
                Right () -> do
                  exists <- doesDirectoryExist destination
                  unchanged <- if exists then sameGeneratedTree destination staging else pure False
                  if unchanged
                    then cleanup >> pure (Right HostUnchanged)
                    else if exists && not force
                      then cleanup >> pure (Left ("host configuration already exists at " <> T.pack destination <> "; pass --force to replace generated scaffolding"))
                      else if exists
                        then replaceDirectory destination staging
                        else renameDirectory staging destination >> pure (Right HostInstalled)
        ) `onException` cleanup

resolveSopsSource :: FilePath -> Maybe FilePath -> IO (Either Text FilePath)
resolveSopsSource destination requested = do
  let candidate = maybe (destination </> "secrets.yaml") id requested
  absolute <- makeAbsolute candidate
  exists <- doesFileExist absolute
  if exists
    then pure (Right absolute)
    else pure (Left ("encrypted sops file not found: " <> T.pack absolute <> "; pass --sops-file when initializing a host"))

validateGeneratedTree :: FilePath -> IO (Either Text ())
validateGeneratedTree root = do
  flakeText <- TIO.readFile (root </> "flake.nix")
  moduleText <- TIO.readFile (root </> "host.nix")
  secretsText <- TIO.readFile (root </> "secrets.yaml")
  let publicText = flakeText <> moduleText
  pure $
    if "PRIVATE KEY" `T.isInfixOf` T.toUpper publicText
      then Left "generated host configuration contains private-key material"
      else if "tskey-" `T.isInfixOf` secretsText
        then Left "refusing plaintext Tailscale token in the host secrets file; encrypt it with sops first"
        else if not ("sops:" `T.isInfixOf` secretsText && "ENC[" `T.isInfixOf` secretsText)
          then Left "host secrets file does not look sops-encrypted (expected sops metadata and ENC[...] values)"
          else Right ()

validateNixFlake :: FilePath -> IO (Either Text ())
validateNixFlake root = do
  processResult <- try (readProcessWithExitCode "nix" ["eval", "path:" <> root <> "#packages.x86_64-linux.nagare-image.drvPath"] "") :: IO (Either IOException (ExitCode, String, String))
  pure $ case processResult of
    Left err -> Left ("could not run nix to validate generated host flake: " <> T.pack (show err))
    Right (ExitSuccess, _, _) -> Right ()
    Right (ExitFailure _, out, err) ->
      Left ("generated host flake failed Nix evaluation:\n" <> T.pack (trimOutput (err <> out)))

sameGeneratedTree :: FilePath -> FilePath -> IO Bool
sameGeneratedTree left right = and <$> traverse same ["flake.nix", "host.nix", "secrets.yaml"]
  where
    same name = do
      leftBytes <- BS.readFile (left </> name)
      rightBytes <- BS.readFile (right </> name)
      pure (leftBytes == rightBytes)

replaceDirectory :: FilePath -> FilePath -> IO (Either Text HostInstallResult)
replaceDirectory destination staging = do
  let parent = takeDirectory destination
  backup <- createTempDirectory parent ".nagare-host.backup."
  removePathForcibly backup
  renameDirectory destination backup
  moved <- try (renameDirectory staging destination) :: IO (Either IOException ())
  case moved of
    Right () -> removePathForcibly backup >> pure (Right HostReplaced)
    Left err -> do
      renameDirectory backup destination
      pure (Left ("could not install generated host configuration; restored previous directory: " <> T.pack (show err)))

removeIfPresent :: FilePath -> IO ()
removeIfPresent path = do
  exists <- doesDirectoryExist path
  when exists (removePathForcibly path)

nixString :: Text -> Text
nixString value = "\"" <> escapeInterpolation (T.concatMap escapeChar value) <> "\""
  where
    escapeChar '"' = "\\\""
    escapeChar '\\' = "\\\\"
    escapeChar '\n' = "\\n"
    escapeChar '\r' = "\\r"
    escapeChar '\t' = "\\t"
    escapeChar c = T.singleton c
    escapeInterpolation = T.replace "${" "\\${"

trimOutput :: String -> String
trimOutput output =
  let outputLines = lines output
  in unlines (take 12 outputLines <> ["..."] <> drop (max 12 (length outputLines - 30)) outputLines)
