{-# LANGUAGE OverloadedStrings #-}

-- | @nagarectl init@ (MasterPlan 12, EP-63): the guided onboarding command. It is
-- the ONE place in nagarectl permitted to drive Pulumi (@pulumi config set@) and
-- gcloud (@services enable@) — a deliberate one-time bootstrap. Every other command
-- resolves its target purely from the environment (see "Nagare.Target").
--
-- Flow (in @runInit@, app/Main.hs): preflight (gcloud auth + operator IAM) ->
-- prompt/resolve the target -> write nagare.target.env (idempotent; --force to
-- clobber) -> run scripts/enable-apis.sh -> @pulumi config set@ the eight keys the
-- infra program reads -> print the ordered next-step commands.
module Nagare.Init
  ( InitOpts (..)
  , WriteResult (..)
  , profileFromOpts
  , renderTargetEnv
  , pulumiConfigSetArgs
  , seedKeys
  , nextStepsText
  , operatorRoles
  , requiredApis
  , writeTargetEnv
  , runPreflight
  , enableApis
  , seedPulumiConfig
  ) where

import Control.Monad (when)
import Data.Function ((&))
import GHC.Generics (Generic)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Text.Encoding (decodeUtf8)
import qualified Data.Text.IO as TIO
import System.Directory (doesFileExist)
import System.Environment (setEnv, unsetEnv)
import System.Exit (ExitCode (..))

import Cradle (addArgs, cmd, run)

import Nagare.Ops.Probe (captureTool)
import Nagare.Target
  ( Mode (..)
  , TargetProfile (..)
  , pulumiBackendToken
  , resolveTargetProfile
  )

-- | Options for @nagarectl init@. The four target flags are 'Maybe' so an absent
-- flag triggers an interactive prompt (on a TTY) or an error (non-TTY). The skip
-- flags exist for testing/CI and for partial recovery (e.g. re-seed without
-- re-enabling). @--force@ permits overwriting an existing profile.
data InitOpts = InitOpts
  { ioContextName :: !(Maybe String)
  , ioProject :: !(Maybe String)
  , ioRegion :: !(Maybe String)
  , ioZone :: !(Maybe String)
  , ioBaseDomain :: !(Maybe String)
  , ioForce :: !Bool
  , ioSkipPreflight :: !Bool
  , ioSkipEnable :: !Bool
  , ioSkipSeed :: !Bool
  , ioDryRun :: !Bool
  }
  deriving stock (Eq, Show, Generic)

-- | The operator IAM roles the preflight verifies (Decision Log). @roles/owner@
-- short-circuits to pass because it includes all of these.
operatorRoles :: [Text]
operatorRoles =
  [ "roles/compute.admin"
  , "roles/dns.admin"
  , "roles/artifactregistry.admin"
  , "roles/storage.admin"
  , "roles/iam.securityAdmin"
  , "roles/serviceusage.serviceUsageAdmin"
  ]

-- | The service APIs enable-apis.sh turns on; kept here for documentation and the
-- next-steps text. The script is the source of truth for the actual enable.
requiredApis :: [Text]
requiredApis =
  [ "compute.googleapis.com"
  , "dns.googleapis.com"
  , "storage.googleapis.com"
  , "artifactregistry.googleapis.com"
  , "iam.googleapis.com"
  , "servicenetworking.googleapis.com"
  ]

-- | Build the resolved 'TargetProfile' from the chosen project/region/zone/base
-- domain by REUSING 'resolveTargetProfile' with those values placed into the
-- environment, so the derived fields (registry host, buckets) follow EP-60's
-- derivations exactly. The derived overrides are cleared so the derivation, not a
-- stale env value, wins.
profileFromOpts :: Text -> Text -> Text -> Text -> IO TargetProfile
profileFromOpts project region zone baseDomain = do
  setEnv "CLOUDSDK_CORE_PROJECT" (T.unpack project)
  setEnv "CLOUDSDK_COMPUTE_REGION" (T.unpack region)
  setEnv "CLOUDSDK_COMPUTE_ZONE" (T.unpack zone)
  setEnv "NAGARE_BASE_DOMAIN" (T.unpack baseDomain)
  mapM_
    unsetEnv
    [ "NAGARE_REGISTRY_HOST"
    , "NAGARE_IMAGE_BUCKET"
    , "NAGARE_BACKUP_BUCKET"
    , "NAGARE_ARTIFACT_REGISTRY_ID"
    , "NAGARE_INSTANCE_NAME"
    ]
  resolveTargetProfile

-- | Render the profile as @export VAR=value@ lines, matching the target/context
-- schema so a profile can round-trip through the context store.
renderTargetEnv :: TargetProfile -> Text
renderTargetEnv tp =
  T.unlines
    [ "# nagare target profile — generated by `nagarectl init` (EP-63)."
    , "# Edit this file or re-run `nagarectl init --force` to change the target."
    , "export CLOUDSDK_CORE_PROJECT=" <> tpProject tp
    , "export CLOUDSDK_COMPUTE_REGION=" <> tpRegion tp
    , "export CLOUDSDK_COMPUTE_ZONE=" <> tpZone tp
    , "export NAGARE_REGISTRY_HOST=" <> tpRegistryHost tp
    , "export NAGARE_ARTIFACT_REGISTRY_ID=" <> tpArtifactRegistryId tp
    , "export NAGARE_IMAGE_BUCKET=" <> tpImageBucket tp
    , "export NAGARE_BACKUP_BUCKET=" <> tpBackupBucket tp
    , "export NAGARE_BASE_DOMAIN=" <> tpBaseDomain tp
    , "export NAGARE_INSTANCE_NAME=" <> tpInstanceName tp
    , "export NAGARE_TARGET_PLATFORM=" <> tpTargetPlatform tp
    , "export NAGARE_MODE=" <> modeToken (tpMode tp)
    , "export NAGARE_LOCAL_OBJECT_STORE=" <> tpLocalObjectStore tp
    , "export NAGARE_PULUMI_BACKEND=" <> pulumiBackendToken (tpPulumiBackend tp)
    , "export NAGARE_PULUMI_BACKEND_URL=" <> tpPulumiBackendUrl tp
    ]
  where
    modeToken Cloud = "cloud"
    modeToken Local = "local"

-- | The eight Pulumi config (key, value) pairs to seed from the profile. Order is
-- stable for deterministic output. @nagare:imageBucket@ is REQUIRED by the program
-- (no default), so it is always present here. NOTE: @NAGARE_TARGET_PLATFORM@ (EP-3)
-- is deliberately NOT seeded — it is a build-time client concern (the architecture
-- nagarectl builds images for), not GCP infrastructure, so Pulumi has no use for it.
seedKeys :: TargetProfile -> [(Text, Text)]
seedKeys tp =
  [ ("gcp:project", tpProject tp)
  , ("gcp:region", tpRegion tp)
  , ("gcp:zone", tpZone tp)
  , ("nagare:baseDomain", tpBaseDomain tp)
  , ("nagare:imageBucket", tpImageBucket tp)
  , ("nagare:backupBucket", tpBackupBucket tp)
  , ("nagare:artifactRegistryId", tpArtifactRegistryId tp)
  , ("nagare:instanceName", tpInstanceName tp)
  ]

-- | The argv for one @pulumi -C infra/pulumi config set --stack STACK KEY VALUE@.
-- Pure so it is unit-testable without Pulumi.
pulumiConfigSetArgs :: Text -> Text -> Text -> [String]
pulumiConfigSetArgs stack key value =
  ["-C", "infra/pulumi", "config", "set", "--stack", T.unpack stack, T.unpack key, T.unpack value]

-- | The ordered follow-on commands printed after a successful init.
nextStepsText :: Text
nextStepsText =
  T.unlines
    [ ""
    , "Next steps:"
    , "  1.  just infra-up        # create the GCP resources (the VM is omitted until the image exists)"
    , "  2.  just host-image      # build + register the NixOS image and write its self-link to Pulumi config"
    , "  3.  just infra-up        # re-run to create the VM now that nagareImageSelfLink is set"
    , "  4.  just cluster-bootstrap   # install the in-cluster platform (k3s/Knative/cert-manager)"
    , ""
    , "See docs/masterplans/12-bring-your-own-gcp-project-onboarding-for-nagare.md and the"
    , "EP-2/EP-3/EP-4 plans under docs/plans/ for the details behind each step."
    ]

-- | Outcome of attempting to write the profile file.
data WriteResult = Wrote | RefusedExists | DryRunWouldWrite
  deriving stock (Eq, Show)

-- | Write nagare.target.env at the repo root, idempotently. Refuses to clobber an
-- existing file unless @force@ is set. With @dryRun@, writes nothing. Returns what
-- it did so the handler can report it.
writeTargetEnv :: Bool -> Bool -> TargetProfile -> IO WriteResult
writeTargetEnv force dryRun tp = do
  let path = "nagare.target.env"
  exists <- doesFileExist path
  if dryRun
    then pure DryRunWouldWrite
    else
      if exists && not force
        then pure RefusedExists
        else do
          TIO.writeFile path (renderTargetEnv tp)
          pure Wrote

-- | Run scripts/enable-apis.sh (which sources the guardrail and enables the APIs).
-- Returns the exit code so the handler can fail the command on a real error. With
-- @dryRun@, sets NAGARE_ENABLE_APIS_DRY_RUN=1 so the script prints the argv. The
-- script's stdout/stderr stream to the terminal (no capture).
enableApis :: Bool -> IO ExitCode
enableApis dryRun = do
  when dryRun (setEnv "NAGARE_ENABLE_APIS_DRY_RUN" "1")
  run $ cmd "bash" & addArgs (["scripts/enable-apis.sh"] :: [String])

-- | @pulumi config set@ each seed key from the profile, against the infra/pulumi
-- stack. Stops and returns the first failing key (with its exit code) so the
-- handler can report a precise, recoverable error. @dryRun@ prints the argv.
seedPulumiConfig :: Bool -> Text -> TargetProfile -> IO (Either (Text, ExitCode) ())
seedPulumiConfig dryRun stack tp = go (seedKeys tp)
  where
    go [] = pure (Right ())
    go ((k, v) : rest)
      | dryRun = do
          TIO.putStrLn ("  pulumi " <> T.pack (unwords (pulumiConfigSetArgs stack k v)))
          go rest
      | otherwise = do
          code <- run $ cmd "pulumi" & addArgs (pulumiConfigSetArgs stack k v)
          case code of
            ExitSuccess -> go rest
            ExitFailure _ -> pure (Left (k, code))

-- | Preflight: confirm gcloud has an active authenticated account and that it
-- holds (or owns) the operator roles on @project@. Returns @Right ()@ on pass, or
-- @Left msg@ with a precise remediation on failure. Read-only: it only queries.
runPreflight :: Text -> IO (Either Text ())
runPreflight project = do
  mAcct <-
    captureTool
      "gcloud"
      ["auth", "list", "--filter=status:ACTIVE", "--format=value(account)"]
  case fmap (T.strip . decodeUtf8) mAcct of
    Nothing -> pure (Left authRemediation)
    Just acct
      | T.null acct -> pure (Left authRemediation)
      | otherwise -> do
          mPolicy <-
            captureTool
              "gcloud"
              [ "projects"
              , "get-iam-policy"
              , T.unpack project
              , "--flatten=bindings[].members"
              , "--filter=bindings.members:user:" <> T.unpack acct
              , "--format=value(bindings.role)"
              ]
          let held = maybe [] (T.lines . T.strip . decodeUtf8) mPolicy
              isOwner = "roles/owner" `elem` held
              missing = filter (`notElem` held) operatorRoles
          if isOwner || null missing
            then pure (Right ())
            else pure (Left (iamRemediation acct project missing))
  where
    authRemediation =
      T.unlines
        [ "nagarectl init preflight FAILED: no active gcloud account."
        , "  Run: gcloud auth login"
        , "  and: gcloud auth application-default login"
        , "  then re-run `nagarectl init`."
        ]
    iamRemediation acct proj missing =
      T.unlines
        ( [ "nagarectl init preflight FAILED: account "
              <> acct
              <> " is missing required roles on "
              <> proj
              <> ":"
          ]
            <> map ("    " <>) missing
            <> [ "  Grant them (or roles/owner), e.g.:"
               , "    gcloud projects add-iam-policy-binding "
                  <> proj
                  <> " --member=user:"
                  <> acct
                  <> " --role=<role>"
               , "  then re-run `nagarectl init` (or pass --skip-preflight to bypass)."
               ]
        )
