apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:qisGohI=,iv:yqJ9vUqnGgDORUxDaBPg3uVRbyFNU0oZ5XDZYJ+WBoI=,tag:+cB4gRHSOjrd21WpO6IYIw==,type:str]
    admin-password: ENC[AES256_GCM,data:yKcRm8TS7sf8ju/8le6qV4LXGkcnCY3vhdOUlvcfw5s=,iv:xFReZXprRcEoCawBhU6E3L5iBxFLw7LLwZ1yvtTYHkg=,tag:RPSXqUkf9wewILIomej/yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR2RCUzI3cXdUOXJ4aitG
            OGJNS21OZ3FHSDl5NUdGRkhFN01laDdXdGd3CnFEUjZ1MG1tS1h1Nk1yR203dy9D
            RXdkYWhKVXM4aDhQVmtWQmhoSDU2VW8KLS0tIFBvWSs2aWx1Qng1VzlyUm1YV3N0
            T3lVbGFqVlNYNFRJU2UwSFgvZ1ZxQkkKSp8bvKG7n66p/P6BR4d6m1mG2FrRc5/I
            122r4vT6WtJS+1PdERh9XveJAmKp1UgQmzdtxMWX092zmLcUW846Gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pqfv2y3u3y66y5zsr3qd7pnxstatvnlnx39nttzksg8kynn4a5tsq9vcsf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T13:37:10Z"
    mac: ENC[AES256_GCM,data:h0X3DqKQVBYPAy2L80OUf1ZQThs1TF4j7eB9JP1DaxXNN1YxwHw/pSU2lB/uY4FpcKp/UZ2rNIwkAcl3kgPvdjGldPQHqP+UEtzC8V+BoyDSDXM6wFha3Gg4cu/7CjUQVWFyiBJcRBIxylASotZgP3FHaR1QWzJeJqbXVliopWY=,iv:aVMk+Vo6uzJGCfsSgG/X6q1Yu9N3x+MzZGCgD4GwbW4=,tag:G/l5jh8JcaN3lAzlXx+E9g==,type:str]
    version: 3.13.1
