apiVersion: v1
kind: Secret
metadata:
    name: notes-db-url
    namespace: personal
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:nMbH3pGAdPhPd0kwQ/x4r4V5DjMhSnQcHkmLkGciAsqvcf9Rs/B/wK+FX9RcCg==,iv:y9MEN2mRFmaLTRnHBerJkTM5LRpo4xUoi3ClPKV3Qkg=,tag:8tHvjf60RDbOuPz9GWtnvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZjZEdUdyNkM1bW9zRGhD
            TEJhellKZktMeXBoSWdwYXlsNHIvVyt1RWhJClIwR2o3MFJZVmZDeDQzUjhVd0VE
            ZTVmdVE2NitubnljQ295WWpLdjBYSkkKLS0tIEZiREp2b3Z0UkNwQVRyUXFEc01z
            MktaVFlpWGJrNDgzVGhzRnM1NFozNnMKfrjwE1it68m2EKH/A812JrpzVCjRYjZo
            ykAmDR+xQxlWC4xNiXxzQzI6Vh9nti/svubj0QTBT3Dy91k3sUx+8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pqfv2y3u3y66y5zsr3qd7pnxstatvnlnx39nttzksg8kynn4a5tsq9vcsf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T04:36:25Z"
    mac: ENC[AES256_GCM,data:4s+5lSFtoW2ZnLkaIrcaJ4zf+67sf8UGOYnQqOV0rdGs2p/0gnBKvc+IWqRiJ1vCDZr7bo3jn1bGm6P3/Vnr1lCUH2Zw5/473lyAEEAPU3O6CX+16IFCwYpxVTbGUqq+p28IekteT6De8oEmob4Rip45YstrXefRNWWksd/cVEQ=,iv:7IS7VCBlpoU5cb/4WcF32DVc0/QOGXatslwlfThPHWM=,tag:scf0mAvvi/WX11WsQmhGWw==,type:str]
    version: 3.13.1
