#!/usr/bin/env python3
"""Actual saved-transaction CLI startup against a conditional GCS recorder.

MP23_SDK=1 uses loopback HTTP; the legacy recorder uses no network.
Provider mutations are rejected. Pass the PruneFixture
artifact directory (generated by run-operational-cost.py prune-fixture).
MP23_COST_BASELINE=1 records the old failure with one unrelated review.
MP23_CLAIM_RACE=acquire injects an identical-head provider-generation race.
MP23_COMPLETE=1 proves completion, journal publication and finalization (SDK only).
MP23_LOST_ACK=1 returns HTTP 500 after each completed conditional publication.
"""
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import time
from inventory_sdk_fixture import StorageFixture, GCLOUD_HELPER

sdk = os.environ.get('MP23_SDK') == '1'
complete = os.environ.get('MP23_COMPLETE') == '1'
lost_ack = os.environ.get('MP23_LOST_ACK') == '1'
assert not complete or sdk, 'completion requires the conditional SDK fixture'
assert not lost_ack or complete, 'lost acknowledgements require the completion path'
emulator = StorageFixture() if sdk else None
repo = Path(__file__).resolve().parents[1]
fixture_root = Path(sys.argv[1]).resolve()
fixture = json.loads((fixture_root / 'fixture.json').read_text())
binary = subprocess.check_output(['cabal', 'list-bin', 'exe:nagarectl', '--enable-tests'],
                                 cwd=repo / 'cli/nagarectl', text=True).strip()
check = subprocess.run(['cabal', 'build', 'exe:nagarectl', 'test:nagarectl-test', '--enable-tests', '--dry-run'],
                       cwd=repo/'cli/nagarectl', capture_output=True, text=True, timeout=30, check=True)
assert 'Up to date' in check.stdout, check.stdout+check.stderr
root = Path(tempfile.mkdtemp(prefix='mp23-active-cost-'))
bins = root / 'bin'
bins.mkdir()
recorder = r'''#!/usr/bin/env python3
import json,os,sys,time
from pathlib import Path
name=Path(sys.argv[0]).name; args=sys.argv[1:]
calls=Path(os.environ['MP23_CALLS'])
with calls.open('a') as f: f.write(json.dumps({'provider':name,'args':args,'at':time.monotonic()})+'\n')
if len(calls.read_text().splitlines())>180: sys.exit(96)
if name=='kubectl':
    if args==['config','current-context']: print('prune-spike'); sys.exit(0)
    if args[:2]==['get','nodes']:
        print(json.dumps({'items':[{'metadata':{'name':'fixture-node','labels':{'node-role.kubernetes.io/control-plane':''}}}]})); sys.exit(0)
    if 'get' in args:
        requested=args[args.index('get')+2]
        for entry in json.loads(Path(os.environ['MP23_FIXTURE']).read_text())['entries']:
            value=entry['native']; meta=value['metadata']
            if meta['name']!=requested: continue
            meta.setdefault('annotations',{}).update({'nagare.dev/context-id':'prune-spike','nagare.dev/resource-id':entry['id'],'nagare.dev/spec-digest':entry['digest']})
            meta.update(uid=entry['uid'],resourceVersion='7')
            if value['kind']=='Job': value['status']={} if entry['prune'] and os.environ.get('MP23_COMPLETE')!='1' else {'conditions':[{'type':'Complete','status':'True'}]}
            print(json.dumps(value)); sys.exit(0)
if name!='gcloud': sys.exit(95)
prefix='gs://audit.invalid/private/'
path=Path(os.environ['MP23_OBJECTS']); objects=json.loads(path.read_text())
if args[:3]==['storage','buckets','describe'] or args[:2]==['projects','describe']: print('12345')
elif args[:3]==['storage','objects','list']:
    print(json.dumps([{'name':'private/'+k[len(prefix):]} for k in objects]))
elif args[:3]==['storage','objects','describe']:
    if args[3] not in objects: sys.exit(1)
    print(objects[args[3]]['generation'])
elif args[:2]==['storage','cp']:
    source,destination=args[2:4]
    if source.startswith(prefix):
        if source.endswith('/*.json'):
            if os.environ.get('MP23_CLAIM_RACE')=='acquire':
                # Same logical head, newer provider generation between the
                # authority read and acquisition. No claimant may hide this ABA.
                objects[prefix+'head.json']['generation'] += 1
                path.write_text(json.dumps(objects))
            for k,v in objects.items():
                if k.startswith(source[:-6]) and k.endswith('.json'): Path(destination,Path(k).name).write_text(v['bytes'])
        elif source in objects: Path(destination).write_text(objects[source]['bytes'])
        else: sys.exit(1)
    elif destination.startswith(prefix):
        # Only head/claim changes are allowed in this unresolved replay.
        if destination != prefix+'head.json': sys.exit(95)
        expected=int(next(a.split('=')[1] for a in args if a.startswith('--if-generation-match=')))
        current=objects.get(destination,{}).get('generation',0)
        if current!=expected: sys.exit(1)
        objects[destination]={'generation':current+1,'bytes':Path(source).read_text()}
        path.write_text(json.dumps(objects)); print(destination+'#'+str(current+1))
    else: sys.exit(95)
else: sys.exit(95)
'''
if sdk:
    recorder = recorder.replace("prefix='gs://audit.invalid/private/'", GCLOUD_HELPER + "prefix='gs://audit.invalid/private/'")
for name in ['gcloud', 'kubectl', 'helm', 'pulumi', 'nix', 'ssh', 'docker', 'curl', 'aws', 'mc']:
    p = bins / name
    p.write_text(recorder)
    p.chmod(0o700)
canonical = lambda value: json.dumps(value, sort_keys=True, separators=(',', ':'))
baseenv = {k: v for k, v in os.environ.items()
           if not k.startswith(('NAGARE_', 'CLOUDSDK_', 'PULUMI_', 'DIRENV_', 'GOOGLE_'))
           and k not in ['KUBECONFIG', 'XDG_CONFIG_HOME', 'XDG_STATE_HOME', 'XDG_CACHE_HOME']}
baseline = os.environ.get('MP23_COST_BASELINE') == '1'
race = os.environ.get('MP23_CLAIM_RACE') == 'acquire'
results = []
for events in ([50] if baseline or race else [50, 500]):
    for reviews in ([0] if race or lost_ack else [0, 1] if baseline else [0, 50, 500]):
        case = root / f'events-{events}-reviews-{reviews}'
        config = case / 'config/nagare'
        (config / 'contexts').mkdir(parents=True)
        (config / 'contexts/prune-spike.env').write_text('CLOUDSDK_CORE_PROJECT=project\nNAGARE_MODE=cloud\nNAGARE_INVENTORY_STORE=gcs\nNAGARE_INVENTORY_STORE_URL=gs://audit.invalid/private\nNAGARE_PLATFORM_VERSION=0.4.0\n')
        host = config / 'hosts/prune-spike'; host.mkdir(parents=True)
        (host / 'host.nix').write_text('{ ... }: {\n  networking = {\n    hostName = "fixture-node";\n  };\n}\n')
        client = 'client-' + 'a'*64
        state = case / 'state/nagare/prune-spike'; state.mkdir(parents=True)
        (state / 'inventory-client-id').write_text(client); (state / 'inventory-client-id').chmod(0o600)
        prefix = 'gs://audit.invalid/private/'
        objects = {prefix+str(p.relative_to(fixture_root/'state/nagare/prune-spike/inventory')):
                   {'generation': 1, 'bytes': p.read_text()}
                   for p in (fixture_root/'state/nagare/prune-spike/inventory').rglob('*.json')}
        objects[prefix+'format.json'] = {'generation': 1, 'bytes': canonical({'version': 1, 'binding': {'identity': 'prune-spike', 'project': 'project'}})}
        head = json.loads(objects[prefix+'head.json']['bytes'])
        head['executorClaim']['clientIdentity'] = client
        prior = None
        for seq in range(events):
            event = json.loads(objects[prefix+f'journal/{seq:020d}.json']['bytes']) if seq < 3 else {
                'version': 1, 'transaction': 'tx-'+'b'*64, 'operation': None,
                'state': {'tag': 'Pending'}, 'timestamp': '2026-09-29T00:00:00Z', 'detail': 'unrelated history'}
            event.update(sequence=seq, previousDigest=prior)
            value = canonical(event); prior = hashlib.sha256(value.encode()).hexdigest()
            objects[prefix+f'journal/{seq:020d}.json'] = {'generation': 1, 'bytes': value}
        head['sequence'] = events
        objects[prefix+'head.json']['bytes'] = canonical(head)
        for n in range(reviews):
            objects[prefix+'reviews/'+hashlib.sha256(f'unrelated-{n}'.encode()).hexdigest()+'.json'] = {'generation': 1, 'bytes': '{}'}
        if reviews and not baseline:
            objects[prefix+'reviews/not-a-digest.json'] = {'generation': 1, 'bytes': 'unrelated invalid key'}
        objfile = case / 'objects.json'
        calls = case / 'calls.jsonl'
        env = dict(baseenv, HOME=str(case/'home'), XDG_CONFIG_HOME=str(case/'config'),
                   XDG_STATE_HOME=str(case/'state'), XDG_CACHE_HOME=str(case/'cache'),
                   NAGARE_PLATFORM_ROOT=str(fixture_root/'payload' if baseline else case/'missing-workspace'), PATH=str(bins)+os.pathsep+baseenv['PATH'],
                   MP23_CALLS=str(calls), MP23_OBJECTS=str(objfile), MP23_FIXTURE=str(fixture_root/'fixture.json'))
        if not sdk: env['NAGARE_INVENTORY_GCS_TRANSPORT'] = 'gcloud'
        if sdk: env['CLOUDSDK_API_ENDPOINT_OVERRIDES_STORAGE'] = emulator.endpoint
        for temperature in ['cold', 'warm']:
            objfile.write_text(json.dumps(objects)); calls.write_text('')
            if sdk: emulator.reset(objects, race=race, head_only=not complete, lost_ack=lost_ack)
            start = time.monotonic()
            p = subprocess.run([binary, '--context', 'prune-spike', 'inventory', 'resume', fixture['transaction'], '--yes'],
                               cwd=case, env=env, text=True, capture_output=True, timeout=25)
            if sdk: objfile.write_text(json.dumps(emulator.objects))
            commands = [json.loads(line) for line in calls.read_text().splitlines()]
            after = json.loads(json.loads(objfile.read_text())[prefix+'head.json']['bytes'])
            row = dict(events=events, reviews=reviews, temperature=temperature, exit=p.returncode,
                       seconds=round(time.monotonic()-start, 3), subprocesses=len(commands),
                       stdout=p.stdout, stderr=p.stderr, commands=commands)
            if sdk: row['http'] = list(emulator.calls)
            def category(command):
                args = command['args']
                if command['provider'] != 'gcloud': return 'providerObservation'
                if args[:3] == ['storage', 'objects', 'list']: return 'objectListing'
                if args[:3] == ['storage', 'buckets', 'describe'] or args[:2] in [['projects', 'describe'], ['config', 'config-helper']] or any('/format.json' in a for a in args): return 'initialization'
                if any('/journal/' in a for a in args): return 'journal'
                if any('/head.json' in a for a in args): return 'headAndClaim'
                return 'immutableEvidence'
            row['callsByCategory'] = {kind: sum(category(c) == kind for c in commands)
                                      for kind in sorted({category(c) for c in commands})}
            results.append(row)
            print(json.dumps({k: v for k, v in row.items() if k not in ['commands', 'http']}), flush=True)
            if race:
                assert p.returncode == 1 and 'head-condition' in p.stderr, row
                assert not any(c['provider'] != 'gcloud' for c in commands), row
                assert after == head, (head, after)
            elif complete:
                assert p.returncode == 0 and p.stdout.strip() == 'converged '+fixture['transaction'] and not p.stderr, row
                assert after['activeTransaction'] is None and after['executorClaim'] is None, after
                assert after['accepted'] == after['converged'] and after['sequence'] > events, after
                final_objects = json.loads(objfile.read_text())
                previous = hashlib.sha256(objects[prefix+f'journal/{events-1:020d}.json']['bytes'].encode()).hexdigest()
                appended = []
                for seq in range(events, after['sequence']):
                    value = final_objects[prefix+f'journal/{seq:020d}.json']['bytes']
                    event = json.loads(value)
                    assert event['sequence'] == seq and event['previousDigest'] == previous, event
                    assert event['transaction'] == fixture['transaction'], event
                    previous = hashlib.sha256(value.encode()).hexdigest()
                    appended.append(event)
                assert appended[-1]['detail'] == 'transaction converged', appended
                assert all(final_objects[k] == v for k, v in objects.items() if not k.endswith('/head.json'))
                assert all(c['provider']=='gcloud' or c['provider']=='kubectl' and ('get' in c['args'] or c['args']==['config','current-context']) for c in commands)
                row['appended'] = appended
                row['finalHead'] = after
            elif not baseline:
                assert p.returncode == 1 and 'ambiguous ' in p.stdout and not p.stderr, row
                assert after['activeTransaction'] == head['activeTransaction'] and after['sequence'] == events
                if sdk:
                    assert sum(c['query'].get('alt') == 'media' and '/private%2Fjournal%2F' in c['path'] for c in emulator.calls) == events
                    assert not any(c['args'][:2] == ['storage', 'cp'] for c in commands)
                    assert sum(c['args'][:2] == ['config', 'config-helper'] for c in commands) == 1
                else:
                    assert len([c for c in commands if c['args'][:2] == ['storage', 'cp'] and c['args'][2].endswith('/journal/*.json')]) == 1
                observed_names = {c['args'][c['args'].index('get')+2] for c in commands if c['provider']=='kubectl' and 'get' in c['args']}
                assert {e['native']['metadata']['name'] for e in fixture['entries'] if e['prune']} <= observed_names, row
                assert not any(c['args'][:3] == ['storage', 'objects', 'list'] for c in commands), row
                active_review = fixture['transaction'][3:]+'.json'
                assert not any('/reviews/' in c['args'][2] and not c['args'][2].endswith(active_review) for c in commands if c['args'][:2] == ['storage', 'cp'])
                assert all(c['provider']=='gcloud' or c['provider']=='kubectl' and ('get' in c['args'] or c['args']==['config','current-context']) for c in commands)
report = {'complete': complete, 'claimRace': race, 'lostAcknowledgement': lost_ack,
          'binarySha256': hashlib.sha256(Path(binary).read_bytes()).hexdigest(),
          'sources': {p: hashlib.sha256((repo/p).read_bytes()).hexdigest() for p in [
              *[str(path.relative_to(repo)) for path in sorted((repo/'cli/nagarectl/app').rglob('*.hs'))],
              'cli/nagarectl/src/Nagare/Inventory/Command.hs',
              'cli/nagarectl/src/Nagare/Inventory/ObservationNative.hs',
              'cli/nagarectl/src/Nagare/Inventory/Status.hs',
              'cli/nagarectl/src/Nagare/Inventory/Execute.hs',
              'cli/nagarectl/src/Nagare/Inventory/Store.hs',
              'scripts/test-inventory-active-command-cost.py']}, 'results': results}
(root/'result.json').write_text(json.dumps(report, indent=2)+'\n')
print('Artifacts: '+str(root))
if complete and not race:
    print('PASS: original transaction converged with chained publication and released claim; no provider effects')
elif not baseline and not race:
    for temperature in ['cold', 'warm']:
        assert len({r['subprocesses'] for r in results if r['temperature']==temperature}) == 1
    if not sdk: assert {r['callsByCategory']['headAndClaim'] for r in results} == {17}, results
    print('PASS: original unresolved transaction; constant command count with unrelated reviews/events; no provider effects')
elif race:
    print('PASS: stale claim observation refused before provider recovery; original head preserved')

if emulator: emulator.close()
