{-# LANGUAGE OverloadedStrings #-}

-- | Postgres managed-database descriptor — the config-as-program surface file a
-- database author ships. @nagarectl@/the loader compiles-and-runs it; every
-- field is built through EP-44's smart constructors, so a bad value is a
-- compile-time or load-time error. The password is NOT here — it is generated by
-- @nagarectl db create@ (EP-45) and lives only in the managed Secret.
module Main (main) where

import Data.Bifunctor (first)
import Nagare.Dsl.Config (emitDatabase)
import Nagare.Dsl.Database
import Nagare.Dsl.Types (RetentionPolicy (..), mkNamespace, mkQuantity)

database :: Either String Database
database = do
  n <- first show (mkDatabaseName "pg-main")
  v <- first show (mkEngineVersion Postgres "18")
  ns <- first show (mkNamespace "personal")
  sz <- first show (mkQuantity "10Gi")
  Right
    Database
      { dbName = n
      , engine = Postgres
      , version = v
      , namespace = ns
      , size = sz
      , resources = Nothing
      , retention = Retain
      }

main :: IO ()
main = case database of
  Left err -> ioError (userError err)
  Right db -> emitDatabase db
