-- | Fixed remote CRI protocol; the operator sends this as one quoted SSH command.
module Nagare.Inventory.ImagePruneScript (imagePruneScript) where

import Data.Text qualified as T
import Nagare.Dsl.Prelude

imagePruneScript :: Text
imagePruneScript =
  T.unlines
    [ "set -euo pipefail"
    , "mode=\"$1\""
    , "expected_instance=\"$2\""
    , "actual_instance=\"$(curl --connect-timeout 5 --max-time 10 -fsS -H Metadata-Flavor:Google http://metadata.google.internal/computeMetadata/v1/instance/id)\""
    , "[ \"$actual_instance\" = \"$expected_instance\" ] || { echo 'image cache VM incarnation differs' >&2; exit 2; }"
    , "containerd_config=\"${NAGARE_CONTAINERD_CONFIG:-/var/lib/rancher/k3s/agent/etc/containerd/config.toml}\""
    , "# Pod sandboxes run the runtime's pause image, which ordinary container"
    , "# listings omit and CRI may report unpinned. Protect every sandbox image,"
    , "# Ready or retained, and the configured sandbox image; any missing or"
    , "# ambiguous observation refuses the whole capture."
    , "sandbox_references() {"
    , "  local pods sandbox inspected configured"
    , "  pods=\"$(k3s crictl pods -o json)\" || return 2"
    , "  jq -e '.items | type == \"array\" and all(.[]; (.id | type == \"string\" and test(\"^[0-9a-f]{64}$\")))' <<<\"$pods\" >/dev/null || return 2"
    , "  while IFS= read -r sandbox; do"
    , "    [ -n \"$sandbox\" ] || continue"
    , "    inspected=\"$(k3s crictl inspectp -o json \"$sandbox\")\" || return 2"
    , "    jq -er '.info.image | select(type == \"string\" and length > 0)' <<<\"$inspected\" || return 2"
    , "  done <<<\"$(jq -r '.items[].id' <<<\"$pods\")\""
    , "  [ -r \"$containerd_config\" ] || return 2"
    , "  configured=\"$(sed -nE 's/^[[:space:]]*(sandbox|sandbox_image)[[:space:]]*=[[:space:]]*\"([^\"]+)\"[[:space:]]*$/\\2/p' \"$containerd_config\" | sort -u)\" || return 2"
    , "  [ -n \"$configured\" ] && [ \"$(wc -l <<<\"$configured\")\" -eq 1 ] || return 2"
    , "  printf '%s\\n' \"$configured\""
    , "}"
    , "capture_cache() {"
    , "  local images containers sandboxes references used='[]' reference observed identity"
    , "  images=\"$(k3s crictl images -o json)\" || return 2"
    , "  containers=\"$(k3s crictl ps -a -o json)\" || return 2"
    , "  sandboxes=\"$(sandbox_references)\" || return 2"
    , "  jq -e '.images | type == \"array\"' <<<\"$images\" >/dev/null || return 2"
    , "  jq -e '.containers | type == \"array\" and all(.[]; (.image.image | type == \"string\" and length > 0))' <<<\"$containers\" >/dev/null || return 2"
    , "  references=\"$({ jq -r '[.containers[] | .image.image, .imageRef, .imageId | select(. != null and . != \"\")] | .[]' <<<\"$containers\" && printf '%s\\n' \"$sandboxes\"; } | sort -u)\" || return 2"
    , "  while IFS= read -r reference; do"
    , "    [ -n \"$reference\" ] || continue"
    , "    observed=\"$(k3s crictl inspecti \"$reference\")\" || return 2"
    , "    identity=\"$(jq -er '.status.id | select(type == \"string\" and test(\"^sha256:[0-9a-f]{64}$\"))' <<<\"$observed\")\" || return 2"
    , "    used=\"$(jq -c --arg identity \"$identity\" '. + [$identity] | unique' <<<\"$used\")\" || return 2"
    , "  done <<<\"$references\""
    , "  jq -ce --arg instance \"$expected_instance\" --argjson used \"$used\" '"
    , "    {cacheInstanceId:$instance, cacheUsedIds:$used,"
    , "     cacheImages:[.images[] | {imageId:.id, imageAliases:(((.repoTags // []) + (.repoDigests // [])) | unique), imagePinned:(.pinned // false)}]}"
    , "    | if all(.cacheImages[]; (.imageId | type == \"string\" and test(\"^sha256:[0-9a-f]{64}$\"))"
    , "         and (.imagePinned | type == \"boolean\") and (.imageAliases | all(.[]; type == \"string\" and length > 0)))"
    , "       and (([.cacheImages[].imageId] | length) == ([.cacheImages[].imageId] | unique | length))"
    , "       and (([.cacheImages[].imageAliases[]] | length) == ([.cacheImages[].imageAliases[]] | unique | length))"
    , "      then . else error(\"invalid image cache observation\") end' <<<\"$images\""
    , "}"
    , "case \"$mode\" in"
    , "  inspect) capture_cache ;;"
    , "  remove)"
    , "    image=\"$3\""
    , "    aliases=\"$4\""
    , "    [[ \"$image\" =~ ^sha256:[0-9a-f]{64}$ ]] || exit 2"
    , "    snapshot=\"$(capture_cache)\""
    , "    count=\"$(jq --arg image \"$image\" '[.cacheImages[] | select(.imageId == $image)] | length' <<<\"$snapshot\")\""
    , "    [ \"$count\" != 0 ] || exit 0"
    , "    jq -e --arg image \"$image\" --argjson aliases \"$aliases\" '"
    , "      .cacheUsedIds as $used"
    , "      | [.cacheImages[] | select(.imagePinned or (.imageId as $id | $used | index($id))) | .imageAliases[]] as $protected"
    , "      | [.cacheImages[] | select(.imageId == $image)] as $selected"
    , "      | ($selected | length) == 1"
    , "        and ($selected[0].imageAliases == $aliases)"
    , "        and ($selected[0].imagePinned == false)"
    , "        and ($used | index($image) | not)"
    , "        and all($selected[0].imageAliases[]; . as $alias | $protected | index($alias) | not)' <<<\"$snapshot\" >/dev/null || {"
    , "      echo 'reviewed image became pinned, used, or changed aliases' >&2; exit 2;"
    , "    }"
    , "    # CRI has no atomic unused-image CAS. Check again in this invocation and"
    , "    # remove only the reviewed full image ID; never use a mutable prune selector."
    , "    k3s crictl rmi \"$image\" >/dev/null"
    , "    ;;"
    , "  *) echo 'unsupported image cache request' >&2; exit 2 ;;"
    , "esac"
    ]
